### ISSUE TITLE
Static js files stored in s3 returning a 404.

### ISSUE THREAD

**Issue by pvautour** [MikeBild/sveltekit-adapter-aws#46]
Hello,

I seem to be having an issue with my deployed project. I have put many days trying to figure it out and make sure it wasn't a user error and am at the point where I can consider the possibility that this is a bug with the project. 

Hopefully this is not the case and someone can point me in the right direction. If there is indeed a bug, I will gladly submit a PR if someone can maybe point me in the right direction or at the very least confirm that this is not a user error.

Thanks,

Pascal V.

# Issue with static js files returning a 404.

The application works fine locally, but returns a 404 for any immutable js ressource.

## Expected Behavior

The application should return all files successfully.

## Current Behavior

- The application works fine locally.
- When doing `npm run build && npm run preview`, the application correctly serves immutable files. Here are some examples:
  - `http://localhost:4173/_app/immutable/entry/index.b8674832.js`. (200 OK)
  - `http://localhost:4173/_app/immutable/entry/start.31ae54a1.js`. (200 OK)
  - `http://localhost:4173/_app/immutable/chunks/singletons.6c175f70.js`. (200 OK)
  - `http://localhost:4173/_app/immutable/nodes/0.436294a1.js`. (200 OK)

- When doing `npm run build` with `autoDeploy: true` in the `svelte.config.js`, the application does not serve immutable files correctly. Here are some examples:
  - `https://xxxxxx1234.execute-<aws-region>.amazonaws.com/_app/immutable/entry/index.b8674832.js`. (404 Not Found)
  - `https://xxxxxx1234.execute-<aws-region>.amazonaws.com/_app/immutable/entry/start.31ae54a1.js`. (404 Not Found)
  - `https://xxxxxx1234.execute-<aws-region>.amazonaws.com/_app/immutable/chunks/singletons.6c175f70.js`. (404 Not Found)
  - `https://xxxxxx1234.execute-<aws-region>.amazonaws.com/_app/immutable/nodes/0.436294a1.js`. (404 Not Found)

- If I look in the s3 bucket containing the static content, i can find the aforementioned files. (xxx-staticcontentbuckete0x12345-1x234x567)
- If I look in my `name-of-app-LambdaServerFunctionHandler-xxx` I see two files: 
  - `index.js` (reference missing files in import statement).
  - `shims.js`
- I have given my lambda function access to s3 manually as a sanity check. 
- Here are the cloudwatch logs from the `LambdaServerFunction`

```
2023-10-03T18:10:06.989Z	bd892315-129f-482a-81e9-415610ebd6fd	ERROR	Error: Not found: /_app/immutable/chunks/stores.ea28bdbc.js
    at resolve (/var/task/index.js:54334:18)
    at resolve (/var/task/index.js:54160:34)
    at Object.#options.hooks.handle (/var/task/index.js:54400:62)
    at respond (/var/task/index.js:54158:43)
```

## Possible Solution

None for now.

## Steps to Reproduce

1. Clone the [repo](git@github.com:Canadian-Geospatial-Platform/app.geo.ca-v2.git)
2. Checkout the commit `22acb3ecc11ac5076bf8e778a28ceee9ece8e0d2`
3. `npm run build`
4. navigate to `https://xxxxxx1234.execute-<aws-region>.amazonaws.com/en-ca/sign-in/receive?code=xxxxxxx-xxxxxxx-xxxxxx-xxxxxx`. (404 Not Found)`
5. look at network requests and cloudwatch for errors.

## Context (Environment)

- This is deployed in a lightly modified aws environment aws cloud environment owned by the canadian federal government.
- The project has a .nvmrc for nodejs v18.17. I believe it is required to match what is available in aws lambda?
- deployed from linux(Arch linux, x86_64, kernel 5.5.5-arch1-1. runs locally on windows and linux (dev and preview).
- The issue happens specifically when returning from an external redirect to an auth provider. navigating the regular website works fine. 

## Description

The application currently returns a 404 when trying to access any immutable file when deployed and returning from an external redirect. It returns the files correctly when running locally. This seems might specifically affect .js files. 

## Attempts at solving the issue

- redeploying everything from scratch
- going back to earlier commits
- ensure that the server handler lambda has access rights to the s3 bucket containing static assets

## Misc questions

- should I use the most recent version of node available instead of the latest supported by aws lambda?

**Comment by pvautour** [comment]
I am no longer using the library. Therefore this issue does not affect me anymore. 

Feel free to reopen it if ever there is value in doing so.
